version: 2
jobs:
  build:
    docker:
          # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
          - image: circleci/golang:1.9

    working_directory: /go/src/rabbitmq-demo

    steps:
          - checkout
          - run: go get github.com/tools/godep
          - run: godep restore
          - run: godep go build
          - store_artifacts:
                    path: /go/src/rabbitmq-demo/rabbitmq-demo
                    destination: builds/rabbitmq-demo

